# Setup
title:        Geospatial Files
tagline:      CPC geospatial file interaction (reading, writing, etc.)
baseurl:      /cpc.geofiles

# About/contact
author:
  name:       Mike Charles
  url:        http://www.github.com/mikecharles

#Others
markdown: kramdown
